
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '5247771F8A0FA2ABFDF356CE2CEA2E5E'
    
_lr_action_items = {'QUOTE':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,33,41,42,],[1,-18,-19,-22,-20,-17,-24,-23,1,-4,1,1,-10,-12,-11,-9,-5,-16,-13,-15,-14,]),'$end':([0,2,3,5,6,7,8,9,10,11,12,13,15,27,28,33,41,42,],[-21,-18,-19,-22,-2,-20,-17,-3,-24,-23,0,-1,-4,-5,-16,-13,-15,-14,]),'NUM':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,29,33,34,36,41,42,],[3,-18,-19,-22,-20,-17,-24,-23,3,-4,3,3,-10,-12,-11,-9,-5,-16,30,-13,35,38,-15,-14,]),'LPAREN':([0,1,2,3,5,7,8,10,11,14,15,16,17,18,19,20,21,22,27,28,31,33,41,42,],[4,14,-18,-19,-22,-20,-17,-24,-23,4,-4,4,25,4,-10,-12,-11,-9,-5,-16,32,-13,-15,-14,]),'TRUE':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,33,41,42,],[5,-18,-19,-22,-20,-17,-24,-23,5,-4,5,5,-10,-12,-11,-9,-5,-16,-13,-15,-14,]),'TEXT':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,33,41,42,],[7,-18,-19,-22,-20,-17,-24,-23,7,-4,7,7,-10,-12,-11,-9,-5,-16,-13,-15,-14,]),'VARI':([25,34,35,],[29,36,37,]),'RPAREN':([2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,23,24,26,27,28,30,31,33,37,38,39,40,41,42,],[-18,-19,-22,-20,-17,-24,-23,-8,-4,-8,-8,-10,-7,-11,-9,27,28,-6,-5,-16,31,33,-13,39,40,41,42,-15,-14,]),'SIMB':([0,2,3,4,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,32,33,41,42,],[8,-18,-19,16,-22,-20,-17,-24,-23,8,-4,8,8,-10,-12,-11,-9,-5,-16,34,-13,-15,-14,]),'NIL':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,33,41,42,],[10,-18,-19,-22,-20,-17,-24,-23,10,-4,10,10,-10,-12,-11,-9,-5,-16,-13,-15,-14,]),'FALSE':([0,2,3,5,7,8,10,11,14,15,16,18,19,20,21,22,27,28,33,41,42,],[11,-18,-19,-22,-20,-17,-24,-23,11,-4,11,11,-10,-12,-11,-9,-5,-16,-13,-15,-14,]),'LET':([4,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'item':([14,16,18,],[18,18,18,]),'bool':([0,14,16,18,],[2,2,2,2,]),'quoted_list':([0,14,16,18,],[6,19,19,19,]),'list':([1,],[15,]),'empty':([14,16,18,],[20,20,20,]),'call':([0,14,16,18,],[9,21,21,21,]),'exp':([0,],[12,]),'atom':([0,14,16,18,],[13,22,22,22,]),'items':([14,16,18,],[23,24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> atom','exp',1,'p_exp_atom','yacc.py',136),
  ('exp -> quoted_list','exp',1,'p_exp_qlist','yacc.py',140),
  ('exp -> call','exp',1,'p_exp_call','yacc.py',144),
  ('quoted_list -> QUOTE list','quoted_list',2,'p_quoted_list','yacc.py',148),
  ('list -> LPAREN items RPAREN','list',3,'p_list','yacc.py',152),
  ('items -> item items','items',2,'p_items','yacc.py',156),
  ('items -> empty','items',1,'p_items_empty','yacc.py',160),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',164),
  ('item -> atom','item',1,'p_item_atom','yacc.py',168),
  ('item -> quoted_list','item',1,'p_item_list','yacc.py',176),
  ('item -> call','item',1,'p_item_call','yacc.py',180),
  ('item -> empty','item',1,'p_item_empty','yacc.py',184),
  ('call -> LPAREN LET LPAREN VARI NUM RPAREN RPAREN','call',7,'p_let_only','yacc.py',188),
  ('call -> LPAREN LET LPAREN VARI NUM RPAREN LPAREN SIMB VARI NUM RPAREN RPAREN','call',12,'p_let_varileft','yacc.py',194),
  ('call -> LPAREN LET LPAREN VARI NUM RPAREN LPAREN SIMB NUM VARI RPAREN RPAREN','call',12,'p_let_variright','yacc.py',204),
  ('call -> LPAREN SIMB items RPAREN','call',4,'p_call','yacc.py',215),
  ('atom -> SIMB','atom',1,'p_atom_simbol','yacc.py',220),
  ('atom -> bool','atom',1,'p_atom_bool','yacc.py',224),
  ('atom -> NUM','atom',1,'p_atom_num','yacc.py',228),
  ('atom -> TEXT','atom',1,'p_atom_word','yacc.py',232),
  ('atom -> <empty>','atom',0,'p_atom_empty','yacc.py',236),
  ('bool -> TRUE','bool',1,'p_true','yacc.py',240),
  ('bool -> FALSE','bool',1,'p_false','yacc.py',244),
  ('atom -> NIL','atom',1,'p_nil','yacc.py',248),
]
